kibana_administrator:
  cluster:
    - monitor
    - manage_security
    - manage_index_templates
  indices:
    - names:
        - "*"
      privileges:
        - read
        - monitor
        - view_index_metadata
        - read_cross_cluster
    - names:
        - "?kibana*"
      privileges:
        - all

filebeats_admin:
  cluster:
    - monitor
    - manage_index_templates
  indices:
    - names:
        - "filebeat-*"
      privileges:
        - all